<a href="https://colab.research.google.com/github/KarlaNCano/Extraccion-de-Datos/blob/main/Extracci%C3%B3n_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [3]:
#Convertir en dataframe
df=pd.read_csv("CountryTable.csv")
#df

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS **

In [5]:
#El filtro 1 "filtro por objeto" fue aplicado en la columna "continent" para obtener los registros que solo contengan la categoria "Asia"
filtro1=df[df["continent"]=="Asia"]
filtro1

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
7,ARE,united Arab Emirates,Asia,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al- Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
9,ARM,Armenia,Asia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert KotSarjan,126.0,AM
16,AZE,Azerbaijan,Asia,Middle East,86600.0,1991.0,7734000,62.9,4127.0,4100.0,Azarbaycan,Federal Republic,Heydar aliyev,144.0,AZ
21,BGD,Bangladesh,Asia,Southern and Central Asia,143998.0,1971.0,129155000,60.2,32852.0,31966.0,Bangladesh,Republic,Shahabuddin Ahmad,150.0,BD
23,BHR,Bahrain,Asia,Middle East,694.0,1971.0,617000,73.0,6366.0,6097.0,Al-Bahrayn,Monarchy (Emirate),Hamad ibn Isa al-Khalifa,149.0,BH
32,BRN,Brunei,Asia,Southeast Asia,5765.0,1984.0,328000,73.6,11705.0,12460.0,Brunei Darussalam,Monarchy (Sultanate),Haji Hassan al-Bolkiah,538.0,BN
33,BTN,Bhutan,Asia,Southern and Central Asia,47000.0,1910.0,2124000,52.4,372.0,383.0,Druk-Yul,Monarchy,Jigme Singye Wangchuk,192.0,BT
41,CHN,China,Asia,Eastern Asia,9572900.0,-1523.0,1277558000,71.4,982268.0,917719.0,Zhongquo,People'sRepublic,Jiang Zemin,1891.0,CN
54,CYP,Cyprus,Asia,Middle East,9251.0,1960.0,754700,76.7,9333.0,8246.0,Kypros/Kibris,Republic,Glafkos Klerides,2430.0,CY
77,GEO,Georgia,Asia,Middle East,69700.0,1991.0,4968000,64.5,6064.0,5924.0,Sakartvelo,Republic,Eduard Sevardnadze,905.0,GE
92,HKG,Hong Kong,Asia,Eastern Asia,1075.0,NaN,6782000,79.5,166448.0,173610.0,Xianggang/Hong Kong,Special Administrative Region of China,Jiang Zemin,937.0,HK
98,IDN,Indonesia,Asia,Southeast Asia,1904569.0,1945.0,212107000,68.0,84982.0,215002.0,Indonesia,Republic,Abdurrahman Wahid,939.0,ID
99,IND,India,Asia,Southern and Central Asia,3287263.0,1947.0,1013662000,62.5,447114.0,430572.0,Bharat/India,Federal Republic,Kocheril Raman Narayanan,1109.0,IN
102,IRN,Iran,Asia,Southern and Central Asia,1648195.0,1906.0,67702000,69.7,195746.0,160151.0,Iran,Islamic Republic,Ali Mohammad Khatami-Ardakani,1380.0,IR
103,IRQ,Iraq,Asia,Middle East,438317.0,1932.0,23115000,66.5,11500.0,NaN,Al- Iraq,Republic,Saddam Hussein al-Takriti,1365.0,IQ
105,ISR,Israel,Asia,Middle East,21056.0,1948.0,6217000,78.6,97477.0,98577.0,Yisrael/Israil,Republic,Moshe Katzav,1450.0,IL
108,JOR,Jordan,Asia,Middle East,88946.0,1946.0,5083000,77.4,7526.0,7051.0,Al-urdunn,Constitutional Monarchy,Abdullah II,1786.0,JO
109,JPN,Japan,Asia,Eastern Asia,377829.0,-660.0,126714000,80.7,3787042.0,4192638.0,Nihon/Nippon,Constitutional Monarchy,Akihito,1532.0,JP
110,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
112,KGZ,Kyrgyzstan,Asia,Southern and Central Asia,199900.0,1991.0,4699000,63.4,1626.0,1767.0,Kyrgyzstan,Republic,Askar Akajev,2253.0,KG
113,KHM,Cambodia,Asia,Southeast Asia,181035.0,1953.0,11168000,56.5,5121.0,5670.0,Kampuchea,Constitutional Monarchy,Norodom Sihanouk,1800.0,KH
116,KOR,South Korea,Asia,Eastern Asia,99434.0,1948.0,46844000,74.4,320749.0,442544.0,Taehan Minguk (Namhan),Republic,Kim Dae-jung,2331.0,KR
117,KWT,Kuwait,Asia,Middle East,17818.0,1961.0,1972000,76.1,27037.0,30373.0,Al-Kuwayt,Constitutional Monarchy (Emirate),Jabir al-Ahmad al-Jabir al-Sabah,2429.0,KW
118,LAO,Laos,Asia,Southeast Asia,236800.0,1953.0,5433000,53.1,1292.0,1746.0,Lao,Republic,Khamtay Siphandone,2432.0,LA
119,LBN,Lebanon,Asia,Middle East,10400.0,1941.0,3282000,71.3,17121.0,15129.0,Lubnan,Republic,emile Lahoud,2438.0,LB
124,LKA,Sri Lanka,Asia,Southern and Central Asia,65610.0,1948.0,18827000,71.8,15706.0,15091.0,Sri Lanka/Ilankai,Republic,Chandrika Kumaratunga,3217.0,LK
129,MAC,Macao,Asia,Eastern Asia,18.0,NaN,473000,81.6,5749.0,5940.0,Macau/Aomen,Special Administrative Region of China,Jiang Zemin,2454.0,MO
134,MDV,Maldives,Asia,Southern and Central Asia,298.0,1965.0,286000,62.2,199.0,NaN,Dhivehi Raajje/Maldives,Republic,Maumoon Abdul Gayoom,2463.0,MV
140,MMR,Myanmar,Asia,Southeast Asia,676578.0,1948.0,45611000,54.9,180375.0,171028.0,Myanma Pye,Republic,kenraali Than Shwe,2710.0,MM
141,MNG,Mongolia,Asia,Eastern Asia,1566500.0,1921.0,2662000,67.3,1043.0,933.0,Mongol uls,Republic,Natsagiin Bagabandi,2696.0,MN
149,MYS,Malaysia,Asia,Southeast Asia,329758.0,1957.0,22244000,70.8,69213.0,97884.0,Malaysia,"Constitutional Monarchy, Federation",Salahuddin Abdul Aziz Shah Alhaj,2464.0,MY
160,NPL,Nepal,Asia,Southern and Central Asia,147181.0,1769.0,23930000,57.8,4768.0,4837.0,Nepal,Constitutional Monarchy,Gyanendra Bir Bikram,2729.0,NP
163,OMN,Oman,Asia,Middle East,309500.0,1951.0,2542000,71.8,16904.0,16153.0,uman,Monarchy (Sultanate),Qabus ibn Sa id,2821.0,OM
164,PAK,Pakistan,Asia,Southern and Central Asia,796095.0,1947.0,156483000,61.1,61289.0,58549.0,Pakistan,Republic,Mohammad Rafiq Tarar,2831.0,PK
168,PHL,Philippines,Asia,Southeast Asia,300000.0,1946.0,75967000,67.5,65107.0,82239.0,Pilipinas,Republic,Gloria Macapagal-Arroyo,766.0,PH
173,PRK,North Korea,Asia,Eastern Asia,120538.0,1948.0,24039000,70.7,5332.0,NaN,Choson Minjujuui In min Konghwaguk (Bukhan),Socialistic Republic,Kim Jong-il,2318.0,KP
176,PSE,Palestine,Asia,Middle East,6257.0,NaN,3101000,71.4,4173.0,NaN,Filastin,Autonomous Area,Yasser (Yasir) Arafat,4074.0,PS
178,QAT,Qatar,Asia,Middle East,11000.0,1971.0,599000,72.4,9472.0,8920.0,Qatar,Monarchy,Hamad ibn Khalifa al-Thani,2973.0,QA
183,SAu,Saudi Arabia,Asia,Middle East,2149690.0,1932.0,21607000,67.8,137635.0,146171.0,Al- Arabiya as-Sa udiya,Monarchy,Fahd ibn Abdul-Aziz al-Sa ud,3173.0,SA
186,SGP,Singapore,Asia,Southeast Asia,618.0,1965.0,3567000,80.1,86503.0,96318.0,Singapore/Singapura/Xinjiapo/Singapur,Republic,Sellapan Rama Nathan,3208.0,SG
203,SYR,Syria,Asia,Middle East,185180.0,1941.0,16125000,68.5,65984.0,64926.0,Suriya,Republic,Bashar al-Assad,3250.0,SY
207,THA,Thailand,Asia,Southeast Asia,513115.0,1350.0,61399000,68.6,116416.0,153907.0,Prathet Thai,Constitutional Monarchy,Bhumibol Adulyadej,3320.0,TH
208,TJK,Tajikistan,Asia,Southern and Central Asia,143100.0,1991.0,6188000,64.1,1990.0,1056.0,Tocikiston,Republic,Emomali Rahmonov,3261.0,TJ
210,TKM,Turkmenistan,Asia,Southern and Central Asia,488100.0,1991.0,4459000,60.9,4397.0,2000.0,Turkmenostan,Republic,Saparmurad Nijazov,3419.0,TM
211,TMP,East Timor,Asia,Southeast Asia,14874.0,NaN,885000,46.0,0.0,NaN,Timor Timur,Administrated by the uN,Jose Alexandre Gusmao,1522.0,TP
215,TuR,Turkey,Asia,Middle East,774815.0,1923.0,66591000,71.0,210721.0,189122.0,Turkiye,Republic,Ahmet Necdet Sezer,3358.0,TR
217,TWN,Taiwan,Asia,Eastern Asia,36188.0,1945.0,22256000,76.4,256254.0,263451.0,Tai-wan,Republic,Chen Shui-bian,3263.0,TW
224,uZB,uzbekistan,Asia,Southern and Central Asia,447400.0,1991.0,24318000,63.7,14194.0,21300.0,uzbekiston,Republic,Islam Karimov,3503.0,uZ
230,VNM,Vietnam,Asia,Southeast Asia,331689.0,1945.0,79832000,69.3,21929.0,22834.0,Viet Nam,Socialistic Republic,Tran Duc Luong,3770.0,VN
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE

In [6]:
#El filtro 2 "filtro por filas" fue aplicado en las filas 10 a 16 no consecutivamente
#filtro2=df.iloc[300:302,:]
filtro2=df.iloc[ 10:16 , : ] #filas no consecutivas
filtro2

,code,name,continent,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
10,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,uS Territory,George W. Bush,54.0,AS
11,ATA,Antarctica,Antarctica,Antarctica,13120000.0,NaN,0,NaN,0.0,NaN,NaN,Co-administrated,NaN,NaN,AQ
12,ATF,French Southern territories,Antarctica,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes francaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
13,ATG,Antigua and Barbuda,North America,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63.0,AG
14,AuS,Australia,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,Au
15,AuT,Austria,Europe,Western Europe,83859.0,1918.0,8091800,77.7,211860.0,206025.0,osterreich,Federal Republic,Thomas Klestil,1523.0,AT

In [7]:
#El filtro 3 "filtro por columnas" fue aplicado en las columnas 1, 4 y 6 no consecutivamente
#filtro3=df.iloc[:,4:7]
filtro3=df.iloc[:,[1,4,6]] #columnas no consecutivas
filtro3

             name  surface_area  population
0           Aruba         193.0      103000
1     Afghanistan      652090.0    22720000
2          Angola     1246700.0    12878000
3        Anguilla          96.0        8000
4         Albania       28748.0     3401200
..            ...           ...         ...
234         Yemen      527968.0    18112000
235    Yugoslavia      102173.0    10640000
236  South Africa     1221037.0    40377000
237        Zambia      752618.0     9169000
238      Zimbabwe      390757.0    11669000

[239 rows x 3 columns]

In [8]:
df= pd.read_csv("CountryTable.csv", index_col=2)
df

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
North America,ABW,Aruba,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Asia,AFG,Afghanistan,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Africa,AGO,Angola,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
North America,AIA,Anguilla,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
Europe,ALB,Albania,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Asia,YEM,Yemen,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
Europe,YuG,Yugoslavia,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu
Africa,ZAF,South Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
Africa,ZMB,Zambia,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Africa,ZWE,Zimbabwe,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [9]:
#El filtro 4 "filtro de filas vs columnas" fue aplicado en la columna "population" para obtener los registros que solo contengan la categoria "Asia" o "Africa"

#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df.loc[["Asia","Africa"], ["population"]]
filtro4

           population
continent
Asia         22720000
Asia          2441000
Asia          3520000
Asia          7734000
Asia        129155000
...               ...
Africa       33517000
Africa       21778000
Africa       40377000
Africa        9169000
Africa       11669000

[109 rows x 1 columns]

In [10]:
#El filtro 5 "filtro por cabecera" fue aplicado en la cabecera
filtro5=df.head(10)
filtro5

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
North America,ABW,Aruba,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Asia,AFG,Afghanistan,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Africa,AGO,Angola,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
North America,AIA,Anguilla,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
Europe,ALB,Albania,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
Europe,AND,Andorra,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,NaN,55.0,AD
North America,ANT,Netherlands Antilles,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,33.0,AN
Asia,ARE,united Arab Emirates,Middle East,83600.0,1971.0,2441000,74.1,37966.0,36846.0,Al-Imarat al- Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65.0,AE
South America,ARG,Argentina,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rua,69.0,AR
Asia,ARM,Armenia,Middle East,29800.0,1991.0,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert KotSarjan,126.0,AM

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [11]:
#El filtro 6 "filtro por comparacion" fue aplicado en la columna "population" para obtener los registros que solo contengan la categoria menor a "2006"
filtro6=df[df["population"]<2006]
filtro6

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
Antarctica,ATA,Antarctica,Antarctica,13120000.0,NaN,0,NaN,0.0,NaN,NaN,Co-administrated,NaN,NaN,AQ
Antarctica,ATF,French Southern territories,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes francaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
Antarctica,BVT,Bouvet Island,Antarctica,59.0,NaN,0,NaN,0.0,NaN,Bouvetoya,Dependent Territory of Norway,Harald V,NaN,BV
Oceania,CCK,Cocos (Keeling) Islands,Australia and New Zealand,14.0,NaN,600,NaN,0.0,NaN,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317.0,CC
South America,FLK,Falkland Islands,South America,12173.0,NaN,2000,NaN,0.0,NaN,Falkland Islands,Dependent Territory of the uK,Elisabeth II,763.0,FK
Antarctica,HMD,Heard Island and McDonald Islands,Antarctica,359.0,NaN,0,NaN,0.0,NaN,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
Africa,IOT,British Indian Ocean Territory,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the uK,Elisabeth II,NaN,IO
Oceania,NFK,Norfolk Island,Australia and New Zealand,36.0,NaN,2000,NaN,0.0,NaN,Norfolk Island,Territory of Australia,Elisabeth II,2806.0,NF
Oceania,NIu,Niue,Polynesia,260.0,NaN,2000,NaN,0.0,NaN,Niue,Nonmetropolitan Territory of New Zealand,Elisabeth II,2805.0,Nu
Oceania,PCN,Pitcairn,Polynesia,49.0,NaN,50,NaN,0.0,NaN,Pitcairn,Dependent Territory of the uK,Elisabeth II,2912.0,PN
Antarctica,SGS,South Georgia and the South Sandwich Islands,Antarctica,3903.0,NaN,0,NaN,0.0,NaN,South Georgia and the South Sandwich Islands,Dependent Territory of the uK,Elisabeth II,NaN,GS
Oceania,TKL,Tokelau,Polynesia,12.0,NaN,2000,NaN,0.0,NaN,Tokelau,Nonmetropolitan Territory of New Zealand,Elisabeth II,3333.0,TK
Oceania,uMI,united States Minor Outlying Islands,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,united States Minor Outlying Islands,Dependent Territory of the uS,George W. Bush,NaN,uM
Europe,VAT,Holy See (Vatican City State),Southern Europe,0.4,1929.0,1000,NaN,9.0,NaN,Santa Sede/Citta del Vaticano,Independent Church State,Johannes Paavali II,3538.0,VA

**FILTROS BASICOS CON CONECTORES LOGICOS**

In [12]:
#El filtro 7 "filtro Y" fue aplicado en la columna "population" para obtener los registros mayores a "100000" y "name" igual a "Aruba"
filtro7=df[(df["population"]>100000) & (df["name"]=="Aruba")]
filtro7

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
North America,ABW,Aruba,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW

In [13]:
#El filtro 8 "filtro O" fue aplicado en la columna "population" para obtener los registros que solo contengan la categoria mayor a "100000" o "name" igual a "Aruba"
filtro8=df[(df["population"]>100000) | (df["name"]=="Aruba")]
filtro8

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
North America,ABW,Aruba,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,129.0,AW
Asia,AFG,Afghanistan,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
Africa,AGO,Angola,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,Jose Eduardo dos Santos,56.0,AO
Europe,ALB,Albania,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqiperia,Republic,Rexhep Mejdani,34.0,AL
North America,ANT,Netherlands Antilles,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Willem-Alexander,33.0,AN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Asia,YEM,Yemen,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,YE
Europe,YuG,Yugoslavia,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav KoStunica,1792.0,Yu
Africa,ZAF,South Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
Africa,ZMB,Zambia,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM
Africa,ZWE,Zimbabwe,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,ZW

In [14]:
#El filtro 9 "filtro NOT" fue aplicado en la columna "population" para no obtener los registros que contengan la categoria mayor o igual "100000" y tampoco "name" igual a "Aruba"
filtro9=df[~(df["population"]>=100000) & ~(df["name"]=="Aruba")]
filtro9

,code,name,region,surface_area,independence_year,population,life_expectancy,gnp,gnp_old,local_name,government_form,head_of_state,capital,code2
continent,,,,,,,,,,,,,,
North America,AIA,Anguilla,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the uK,Elisabeth II,62.0,AI
Europe,AND,Andorra,Southern Europe,468.0,1278.0,78000,83.5,1630.0,NaN,Andorra,Parliamentary Coprincipality,NaN,55.0,AD
Oceania,ASM,American Samoa,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,uS Territory,George W. Bush,54.0,AS
Antarctica,ATA,Antarctica,Antarctica,13120000.0,NaN,0,NaN,0.0,NaN,NaN,Co-administrated,NaN,NaN,AQ
Antarctica,ATF,French Southern territories,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes francaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
North America,ATG,Antigua and Barbuda,Caribbean,442.0,1981.0,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63.0,AG
North America,BMu,Bermuda,North America,53.0,NaN,65000,76.9,2328.0,2190.0,Bermuda,Dependent Territory of the uK,Elisabeth II,191.0,BM
Antarctica,BVT,Bouvet Island,Antarctica,59.0,NaN,0,NaN,0.0,NaN,Bouvetoya,Dependent Territory of Norway,Harald V,NaN,BV
Oceania,CCK,Cocos (Keeling) Islands,Australia and New Zealand,14.0,NaN,600,NaN,0.0,NaN,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317.0,CC
Oceania,COK,Cook Islands,Polynesia,236.0,NaN,20000,71.1,100.0,NaN,The Cook Islands,Nonmetropolitan Territory of New Zealand,Elisabeth II,583.0,CK
Oceania,CXR,Christmas Island,Australia and New Zealand,135.0,NaN,2500,NaN,0.0,NaN,Christmas Island,Territory of Australia,Elisabeth II,1791.0,CX
North America,CYM,Cayman Islands,Caribbean,264.0,NaN,38000,78.9,1263.0,1186.0,Cayman Islands,Dependent Territory of the uK,Elisabeth II,553.0,KY
North America,DMA,Dominica,Caribbean,751.0,1978.0,71000,73.4,256.0,243.0,Dominica,Republic,Vernon Shaw,586.0,DM
South America,FLK,Falkland Islands,South America,12173.0,NaN,2000,NaN,0.0,NaN,Falkland Islands,Dependent Territory of the uK,Elisabeth II,763.0,FK
Europe,FRO,Faroe Islands,Nordic Countries,1399.0,NaN,43000,78.4,0.0,NaN,Foroyar,Part of Denmark,Margrethe II,901.0,FO
Europe,GIB,Gibraltar,Southern Europe,6.0,NaN,25000,79.0,258.0,NaN,Gibraltar,Dependent Territory of the uK,Elisabeth II,915.0,GI
North America,GRD,Grenada,Caribbean,344.0,1974.0,94000,64.5,318.0,NaN,Grenada,Constitutional Monarchy,Elisabeth II,916.0,GD
North America,GRL,Greenland,North America,2166090.0,NaN,56000,68.1,0.0,NaN,Kalaallit Nunaat/Gronland,Part of Denmark,Margrethe II,917.0,GL
Antarctica,HMD,Heard Island and McDonald Islands,Antarctica,359.0,NaN,0,NaN,0.0,NaN,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
Africa,IOT,British Indian Ocean Territory,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the uK,Elisabeth II,NaN,IO
Oceania,KIR,Kiribati,Micronesia,726.0,1979.0,83000,59.8,40.7,NaN,Kiribati,Republic,Teburoro Tito,2256.0,KI
North America,KNA,Saint Kitts and Nevis,Caribbean,261.0,1983.0,38000,70.7,299.0,NaN,Saint Kitts and Nevis,Constitutional Monarchy,Elisabeth II,3064.0,KN
Europe,LIE,Liechtenstein,Western Europe,160.0,1806.0,32300,78.8,1119.0,1084.0,Liechtenstein,Constitutional Monarchy,Hans-Adam II,2446.0,LI
Europe,MCO,Monaco,Western Europe,1.5,1861.0,34000,78.8,776.0,NaN,Monaco,Constitutional Monarchy,Rainier III,2695.0,MC
Oceania,MHL,Marshall Islands,Micronesia,181.0,1990.0,64000,65.5,97.0,NaN,Marshall Islands/Majol,Republic,Kessai Note,2507.0,MH
Oceania,MNP,Northern Mariana Islands,Micronesia,464.0,NaN,78000,75.5,0.0,NaN,Northern Mariana Islands,Commonwealth of the uS,George W. Bush,2913.0,MP
North America,MSR,Montserrat,Caribbean,102.0,NaN,11000,78.0,109.0,NaN,Montserrat,Dependent Territory of the uK,Elisabeth II,2697.0,MS
Oceania,NFK,Norfolk Island,Australia and New Zealand,36.0,NaN,2000,NaN,0.0,NaN,Norfolk Island,Territory of Australia,Elisabeth II,2806.0,NF
Oceania,NIu,Niue,Polynesia,260.0,NaN,2000,NaN,0.0,NaN,Niue,Nonmetropolitan Territory of New Zealand,Elisabeth II,2805.0,Nu
Oceania,NRu,Nauru,Micronesia,21.0,1968.0,12000,60.8,197.0,NaN,Naoero/Nauru,Republic,Bernard Dowiyogo,2728.0,NR
Oceania,PCN,Pitcairn,Polynesia,49.0,NaN,50,NaN,0.0,NaN,Pitcairn,Dependent Territory of the uK,Elisabeth II,2912.0,PN
Oceania,PLW,Palau,Micronesia,459.0,1994.0,19000,68.6,105.0,NaN,Belau/Palau,Republic,Kuniwo Nakamura,2881.0,PW
Antarctica,SGS,South Georgia and the South Sandwich Islands,Antarctica,3903.0,NaN,0,NaN,0.0,NaN,South Georgia and the South Sandwich Islands,Dependent Territory of the uK,Elisabeth II,NaN,GS
Africa,SHN,Saint Helena,Western Africa,314.0,NaN,6000,76.8,0.0,NaN,Saint Helena,Dependent Territory of the uK,Elisabeth II,3063.0,SH
Europe,SJM,Svalbard and Jan Mayen,Nordic Countries,62422.0,NaN,3200,NaN,0.0,NaN,Svalbard og Jan Mayen,Dependent Territory of Norway,Harald V,938.0,SJ
Europe,SMR,San Marino,Southern Europe,61.0,885.0,27000,81.1,510.0,NaN,San Marino,Republic,NaN,3171.0,SM
North America,SPM,Saint Pierre and Miquelon,North America,242.0,NaN,7000,77.6,0.0,NaN,Saint-Pierre-et-Miquelon,Territorial Collectivity of France,Jacques Chirac,3067.0,PM
Africa,SYC,Seychelles,Eastern Africa,455.0,1976.0,77000,70.4,536.0,539.0,Sesel/Seychelles,Republic,France-Albert Rene,3206.0,SC
North America,TCA,Turks and Caicos Islands,Caribbean,430.0,NaN,17000,73.3,96.0,NaN,The Turks and Caicos Islands,Dependent Territory of the uK,Elisabeth II,3423.0,TC
Oceania,TKL,Tokelau,Polynesia,12.0,NaN,2000,NaN,0.0,NaN,Tokelau,Nonmetropolitan Territory of New Zealand,Elisabeth II,3333.0,TK
Oceania,TON,Tonga,Polynesia,650.0,1970.0,99000,67.9,146.0,170.0,Tonga,Monarchy,Taufa'ahau Tupou IV,3334.0,TO
Oceania,TuV,Tuvalu,Polynesia,26.0,1978.0,12000,66.3,6.0,NaN,Tuvalu,Constitutional Monarchy,Elisabeth II,3424.0,TV
Oceania,uMI,united States Minor Outlying Islands,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,united States Minor Outlying Islands,Dependent Territory of the uS,George W. Bush,NaN,uM
Europe,VAT,Holy See (Vatican City State),Southern Europe,0.4,1929.0,1000,NaN,9.0,NaN,Santa Sede/Citta del Vaticano,Independent Church State,Johannes Paavali II,3538.0,VA
North America,VGB,"Virgin Islands, British",Caribbean,151.0,NaN,21000,75.4,612.0,573.0,British Virgin Islands,Dependent Territory of the uK,Elisabeth II,537.0,VG
North America,VIR,"Virgin Islands, u.S.",Caribbean,347.0,NaN,93000,78.1,0.0,NaN,Virgin Islands of the united States,uS Territory,George W. Bush,4067.0,VI
Oceania,WLF,Wallis and Futuna,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF

In [15]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("Entregable1.csv")